server.port=8083
spring.application.name=auth-service

grpc.client.user-service.address=static://${USER_SERVICE_GRPC_HOST:localhost}:${USER_SERVICE_GRPC_PORT:9090}
grpc.client.user-service.negotiation-type=plaintext

jwt.secret=${JWT_SECRET:min-super-hemliga-nyckel-som-ingen-far-veta-om-12345}