server:
  port: 8082

spring:
  application:
    name: message-service

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: guest
    password: guest

  # Databaskonfiguration för Message Service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/messagedb
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true


grpc:
  client:
    user-service:
      address: 'static://user-service:9090'
      negotiation-type: plaintext
