# 1. Gemensamma inställningar för alla tjänster
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatapp-config
data:
  # Host-namn för tjänsterna (matchar namnen på Services nedan)
  RABBITMQ_HOST: "rabbitmq-service"
  USER_SERVICE_GRPC_HOST: "user-service"
  AUTH_SERVICE_HOST: "auth-service"
  USER_SERVICE_HOST: "user-service"
  MESSAGE_SERVICE_HOST: "message-service"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "user"
  POSTGRES_DB: "userdb"
  POSTGRES_PASSWORD: "password"
  AUTH_SERVER_ISSUER_URI: "http://chatapp.local/auth"
  AUTH_SERVER_INTERNAL_JWK_URI: "http://auth-service:8083/auth/oauth2/jwks"

  # Portar
  RABBITMQ_PORT: "5672"
  USER_SERVICE_GRPC_PORT: "9090"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE DATABASE userdb;
    CREATE DATABASE messagedb;

---

# 2. RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management # Inkluderar webb-gränssnitt
          ports:
            - containerPort: 5672 # AMQP (trafik)
            - containerPort: 15672 # Management UI (webb)

---

# 3. RabbitMQ Service (Gör servern nåbar i nätverket)
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672

---

# 4. PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-init-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init-volume
          configMap:
            name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432