server.port=8081
spring.application.name=user-service

grpc.server.port=${GRPC_SERVER_PORT:9090}

spring.datasource.url=jdbc:h2:mem:userdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update