server:
  port: 8081 # Porten för eventuella REST/hälso-endpoints

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL # Kör databasen helt i RAM-minnet så länge
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true # Gör att du kan surfa in på localhost:8081/h2-console och titta på databasen
      path: /users/h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Skapar tabellerna automatiskt i H2 baserat på vår UserEntity
    show-sql: true

# Här konfigurerar vi gRPC-servern!
grpc:
  server:
    port: 9090 # gRPC-servern körs på denna port